export const plans = [
  {
    id: '0',
    title: 'Core',
    priceMonthly: 19,
    priceYearly: 12,
    caption: 'Best for solo creators',
    features: [
      '100MB Cloud storage',
      '100+ prompt templates',
      '5 projects',
      '24/7 support',
    ],
    icon: '/images/circle.svg',
    logo: '/images/plan-1.webp',
  },
  {
    id: '1',
    title: 'Overdrive',
    priceMonthly: 79,
    priceYearly: 59,
    caption: 'Most popular plan',
    features: [
      'All Starter features',
      '1TB additional storage',
      'Unlimited projects',
      'Analytics',
    ],
    icon: '/images/triangle.svg',
    logo: '/images/plan-2.webp',
  },
  {
    id: '2',
    title: 'Team',
    priceMonthly: 39,
    priceYearly: 29,
    caption: 'Exclusively for teams',
    features: [
      'All Overdrive features',
      '10TB additional storage',
      '50% off per member',
      'Real-time collaboration',
    ],
    icon: '/images/hexagon.svg',
    logo: '/images/plan-3.webp',
  },
];
